worker_processes 1;

events {
    worker_connections 1024;
}

http {

    # Docker interner DNS-Server
    resolver 127.0.0.11 valid=30s ipv6=off;

    # Fehlerseiten für Backends
    root /usr/share/nginx/html;
    index index.html;

    # HTTP Weiterleitungen auf HTTPS
    server {
        listen 80;
        server_name railhq.io localhost;
        return 301 https://$host$request_uri;
    }

    # TLS Terminierung für railhq.io (index)
    server {
        listen 443 ssl;
        server_name railhq.io localhost;

        error_page 502 504 /issues.html;
        location /issues.html {
            root /usr/share/nginx/html/runtime;
            internal;
        }

        # Zertifikat und Schlüssel für TLS
        ssl_certificate /etc/nginx/certificates/railhq-local.crt;
        ssl_certificate_key /etc/nginx/certificates/railhq-local.key;

        # Sicherheitsoptionen
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:ECDHE-RSA-AES128-GCM-SHA256';
        ssl_prefer_server_ciphers on;

        # Weiterleitung zu Index (intern auf Port 443)
        location / {
            set $backend "https://index:443";
            proxy_pass $backend;

            proxy_ssl_verify off;
            proxy_ssl_server_name on;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
