<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\libInterop\libInterop.csproj" />
    <ProjectReference Include="..\libShared\libShared.csproj" />
  </ItemGroup>

</Project>
