// Copyright (c) 2025 Dr. Christian Benjamin Ries
// Licensed under the MIT License
// See LICENSE file in the project root for full license information.

using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace railyWebApp.Controller
{
    /// <summary>
    /// Controller for providing configuration values to JavaScript clients.
    /// </summary>
    [Route("api/[controller]")]
    [ApiController]
    public class ConfigController : ControllerBase
    {
        /// <summary>
        /// Returns a JavaScript file with configuration constants.
        /// This allows the JavaScript code to use server-side configuration values.
        /// </summary>
        /// <returns>JavaScript content with configuration constants</returns>
        [HttpGet("globals.js")]
        [Produces("application/javascript")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public IActionResult GetGlobalsJs()
        {
            var config = HostConfiguration.Current;
            
            var js = $@"// Auto-generated configuration from server
// Do not edit this file directly - values come from appsettings.json
const constGitWebsite = ""{EscapeJs(config.WebsiteUrl)}"";
const constGitWikiWebsite = ""{EscapeJs(config.WikiUrl)}"";
";
            
            return Content(js, "application/javascript");
        }
        
        /// <summary>
        /// Returns configuration as JSON object
        /// </summary>
        [HttpGet("host")]
        [Produces("application/json")]
        [ProducesResponseType(StatusCodes.Status200OK)]
        public IActionResult GetHostConfig()
        {
            var config = HostConfiguration.Current;
            return Ok(new
            {
                websiteUrl = config.WebsiteUrl,
                wikiUrl = config.WikiUrl,
                domain = config.Domain
            });
        }
        
        private static string EscapeJs(string value)
        {
            if (string.IsNullOrEmpty(value)) return "";
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\n", "\\n")
                .Replace("\r", "\\r");
        }
    }
}
