// Copyright (c) 2025 Dr. Christian Benjamin Ries
// Licensed under the MIT License
// See LICENSE file in the project root for full license information.

﻿//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace railySystray.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("railySystray.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About railhq.io.
        /// </summary>
        internal static string AboutRaily {
            get {
                return ResourceManager.GetString("AboutRaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An active process has been detected and successfully linked to the system tray instance..
        /// </summary>
        internal static string AppFoundMessage {
            get {
                return ResourceManager.GetString("AppFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CmdExit {
            get {
                return ResourceManager.GetString("CmdExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help &amp;&amp; FAQ.
        /// </summary>
        internal static string CmdHelp {
            get {
                return ResourceManager.GetString("CmdHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to railhq.io.
        /// </summary>
        internal static string DialogTitle {
            get {
                return ResourceManager.GetString("DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to railhq.io - Error.
        /// </summary>
        internal static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string LinkConfiguration {
            get {
                return ResourceManager.GetString("LinkConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispatcher Panel.
        /// </summary>
        internal static string LinkDispatcherPanel {
            get {
                return ResourceManager.GetString("LinkDispatcherPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The railhq.io gateway process has stopped..
        /// </summary>
        internal static string ProcessStopped {
            get {
                return ResourceManager.GetString("ProcessStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Gateway.
        /// </summary>
        internal static string RestartGateway {
            get {
                return ResourceManager.GetString("RestartGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Gateway.
        /// </summary>
        internal static string StartGateway {
            get {
                return ResourceManager.GetString("StartGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Gateway.
        /// </summary>
        internal static string StopGateway {
            get {
                return ResourceManager.GetString("StopGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to railhq.io Gateway.
        /// </summary>
        internal static string SystrayTooltipTitle {
            get {
                return ResourceManager.GetString("SystrayTooltipTitle", resourceCulture);
            }
        }
    }
}
