<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyTitle>railhq.io - ESU Driver</AssemblyTitle>
    <AssemblyName>railhqEsu</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Libraries\libEsuEcos\libEsuEcos.csproj" />
    <ProjectReference Include="..\..\Libraries\libInterop\libInterop.csproj" />
    <ProjectReference Include="..\..\Libraries\libUtilities\libUtilities.csproj" />
  </ItemGroup>

</Project>
